#!/bin/bash

set -eux
set -o pipefail

systemctl enable cloud-init-local.service
systemctl enable cloud-init-main.service
systemctl enable cloud-init-network.service
systemctl enable cloud-config.service
systemctl enable cloud-final.service
